
#define IDR_MENU                        101
#define IDI_ICON                        102
#define IDC_ABORT                       40001
#define IDC_VISION                      40002
#define IDC_SERVER                      40003
#define IDC_CONNECT                     40004
#define IDC_SINGLE                      40006
#define IDC_MULTI                       40007
#define IDC_EXIT                        40008
#define IDC_COREAUTO                    40009
#define IDC_FIRST                       40010
#define IDC_RESET                       40011
#define IDC_RESTORATION                 40013

#define IDC_WHITE                       40014
#define IDC_BLACK                       40015
#define IDC_BENCHMARK                   40016

#define IDC_LEVELEASY                   40017
#define IDC_LEVELSTANDARD               40018
#define IDC_LEVELHARD                   40019

#define IDC_1CORE                       40020
#define IDC_2CORES                      40021
#define IDC_4CORES                      40022


